### ISSUE TITLE
Meta Data seems to be changing 

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#10]
In looking at the "view all reports" page from the management home, I notice that around 17-008 there is a noticeable decline in the reports showing an instructor or student name.  Is this because we stopped requiring those data points be entered before?  They are not currently required.  And they history of reports show that the reporters usually put this data in.

**Comment by jfrabell** [comment]
I will troubleshoot and fix 10, 11 and 12 this week.  I am quietly working on more comprehensive reforms to the system where adding or changing one thing doesn't break something else.  The changing one thing breaks something else has been going on for a while.

**Comment by rkavalhuna** [comment]
Great.  Thanks.

Russ Kavalhuna
Executive Director of Flight Operations
Western Michigan University College of Aviation
269-377-5031(c)

**Comment by jfrabell** [comment]
Instructor name / student name were no longer on the form.  This mistake occurred when I discovered that if a user selected "No" to all four questions, they were presented with a blank form.  When I corrected this, I forgot to add the words "tree =" to a query.  Totally my fault.  Fixed.

Billable time:  0.
