### ISSUE TITLE
Practice site

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#10]
Jeff,

I colleague recently suggested building an off shoot site where a user could use a practice site that mirrors the real sight so as to learn and mess with the functionality without sending a fake report to me and the other committee members upon submission?  This set aside would, of course, need bold language about this not being a real reporting page.  This would help professors and CFI's in teaching the CASRS system to students. 

Thoughts?

**Comment by jfrabell** [comment]
I can do this.  I will put a duplicate site together with full functionality, and we can easily remove any features you don't want on the duplicate.  Expect action on this by Friday, 1/27/17

**Comment by rkavalhuna** [comment]
Great.  Thanks.

Russ Kavalhuna
Executive Director of Flight Operations
Western Michigan University
College of Aviation
269.377.5031

On Jan 24, 2017, at 5:30 PM, jfrabell <notifications@github.com<mailto:notifications@github.com>> wrote:


I can do this. I will put a duplicate site together with full functionality, and we can easily remove any features you don't want on the duplicate. Expect action on this by Friday, 1/27/17

-

**Comment by jfrabell** [comment]
Site is built.  Link http://www.wmich.edu/aviation/asrs/trainer 

Issue closed.
