### ISSUE TITLE
Event Types are not coming through 

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#12]
When looking at all reports in the management home, it is clear that "event types" are not coming through to the meta data page (the view all reports page).  Event type is still a required entry, but reporters are not inserting an entry here.  Can't figure why or what is wrong.  It appears that the event types stopped being reported and showing up this page around 17-008.

**Comment by jfrabell** [comment]
This is the same error that was causing issue 10.  Corrected.

Billable 0.
