### ISSUE TITLE
Names still not coming up in CASRS reports 

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#14]
I suspect the form is still not soliciting names.

**Comment by jfrabell** [comment]
You are absolutely correct.  This tested good when I closed the last issue.  Looking into this right now.

**Comment by jfrabell** [comment]
I completely rewrote the logic that creates the questions from the logic tree.  Tested working, but I'm going to leave the issue open for a week or so to verify it is working.  

If "Intent for flight" is selected 'Yes', the student name and instructor name are appearing on the form for me.

Jeff
