### ISSUE TITLE
Still having some reports show 

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#15]
Dates and times of December 31st, 1969

17-025, 032, 037.

**Comment by jfrabell** [comment]
I believe this is occurring when a date is not selected upon submission.  I will correct this issue tomorrow, 2/21/17.

**Comment by jfrabell** [comment]
Fields of decision tree 'Required' (show up regardless of decision tree) were not being tested for required entry.  This is fixed.  I will close this issue if no more 1969 reports show up in the next few weeks.
