### ISSUE TITLE
Strange entry in details of report

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#17]
When viewing the full details of some reports (e.g., 17-032) the phrase "This report has been deleted." is included.  

I haven't seen this before and don't know what it means or where it came from.

**Comment by jfrabell** [comment]
I looked at a sample of 100 reports including 17-032 and did not encounter this error.   I may have been in the system when you encountered it, or another code change has fixed this.  Closing for now.  Please let me know if it recurs.

**Comment by rkavalhuna** [comment]
Roger.  Thanks.

Russ Kavalhuna
Executive Director of Flight Operations
Western Michigan University College of Aviation
269-377-5031(c)
