### ISSUE TITLE
Color Coding

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#18]
Can we have the "view details" parts of the reports show not only what the voting members agreed upon regarding causal factor, but also the level-of-risk color?

**Comment by jfrabell** [comment]
Process started with the latest reviewer's choice of level of risk displaying.  Issues remaining, should only display when agreed upon and should only display when data is available.

**Comment by jfrabell** [comment]
Copying your comment 

I like how under analyze data, we can see how many reports are in each category for the last number of weeks. The X axis is meant to list the different colors, but I think it needs some coding for those headings. I'd also like to be able to click the numbers in the graph to populate a list of the actual reports that support that number, like the causal-factor historical matrix has.

Closing the other issue as a duplicate
