### ISSUE TITLE
Assignment and email notification

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#23]
Tom Grossman and Scot Austin experienced a problem when they were both assigned a report recently (by me).  Neither were sent email noting this assignment.  Both could only find it by looking behind the veil that their respective authorities allowed.  Austin looking at the list that populated what he had to review.  Grossman by looking at the distribution list.

**Comment by jfrabell** [comment]
I just submitted a test report and assigned it to you and me.  I received the email.  Let me know if this issue continues for them.  I'm closing this for now, will reopen if necessary.
