### ISSUE TITLE
Risk matrix issues

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#26]
When I go to the risk matrix, I cannot click on a number depicted (say in those reds for the last weeks) to see what reports were called red.  When you click a number, it shows unusable data.  

Thanks,

**Comment by jfrabell** [comment]
This is giving me more headaches than I anticipated.  I have removed the link in the matrix until I can get this sorted properly.

Jeff

**Comment by rkavalhuna** [comment]
Hi, Jeff.  Any thoughts on this?  I'd like to be able to use this function, if at all possible.  Thanks.

**Comment by jfrabell** [comment]
The feature works as expected now.  Let me know if you would like anything added or changed.  Closing the issue.

**Comment by rkavalhuna** [comment]
Thanks.

Russ Kavalhuna
Executive Director of Flight Operations
Western Michigan University
College of Aviation
269.377.5031

On Jun 29, 2017, at 2:29 AM, Jeff Frabell <notifications@github.com<mailto:notifications@github.com>> wrote:


The feature works as expected now. Let me know if you would like anything added or changed. Closing the issue.
