### ISSUE TITLE
System problems

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#7]
System showed various functionality problems.

System not successfully populating list under management and view all reports.

When selecting assign reports, system cannot pull of details in the new tab when selective view details.

**Comment by jfrabell** [comment]
The specifics you mentioned here have been addressed.  I'm going to leave this issue open for anything else that pops up.

**Comment by rkavalhuna** [comment]
Jeff,

Should the below requests be run through the wiki you set up?

1-The test site/sandbox is great.  Can you link it at the bottom left of the screen that a user sees after logging into the real site?  That will increase utility.

2-Can we changes the name of the rainbow of risk selection for reviews to call it "Risk Assessment"?

3-Can we add a question mark after that risk assessment option that says:

Green = you believe this is either not a true safety issue or a safety issue that is low enough of a risk that is inherent in the operation of aircraft.

Yellow = you believe this safety risk is worthy of notice, discussion, and possible action if it is repeated.

Red = you believe this safety risk is unacceptably high and the college community and/or the parties involved need immediate counseling and reaction.

Russ Kavalhuna
Executive Director of Flight Operations
Western Michigan University College of Aviation
269-377-5031(c)

**Comment by jfrabell** [comment]
The wiki is intended to grow into a user manual of sorts.  Keep issues in here.   If I were to ask you to change anything about this particular request it would be to make feature requests separate issues.  Not a big deal because I don't have a team of developers.  I'll get this stuff done Monday or Tuesday.

**Comment by rkavalhuna** [comment]
Perfect.  Thanks.

Russ Kavalhuna
Executive Director of Flight Operations
Western Michigan University
College of Aviation
269.377.5031

On Feb 5, 2017, at 9:16 AM, Jeff Frabell <notifications@github.com<mailto:notifications@github.com>> wrote:


The wiki is intended to grow into a user manual of sorts. Keep issues in here. If I were to ask you to change anything about this particular request it would be to make feature requests separate issues. Not a big deal because I don't have a team of developers. I'll get this stuff done Monday or Tuesday.

**Comment by jfrabell** [comment]
All requests on this thread are complete.  I'm going to close this.  Any new issues / needs can be opened in new issues.

--coding time 35 minutes.
