### ISSUE TITLE
Severity of report - color coding

### ISSUE THREAD

**Issue by tgrossman** [jfrabell/CASRS#8]
This might just be a "growing pains" issue but there have been a few times that I have reviewed a report before selecting the severity color.  Should the system have a default value of "null" and then require a change to red, yellow or green?  Just a thought.  BTW, I like the change.

**Comment by jfrabell** [comment]
That's a great idea.  I'll get that coded ASAP

**Comment by jfrabell** [comment]
Severity of report now defaults to "--"
