### ISSUE TITLE
Threat level marking

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#9]
Jeff,

Where you able to contemplate my request to allow committee members to rate the level of risk that is associated with a CASRS report that they are reviewing?

**Comment by jfrabell** [comment]
This is on my list.  I intend to work this issue in the next 7 days.

**Comment by jfrabell** [comment]
Basic functionality is in place.  I'm going to close this issue.  Any bugs with this feature can be opened as new issues.
